version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: task-management-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: taskmanagement
    volumes:
      - mongodb_data:/data/db
    networks:
      - task-management-network

  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: task-management-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - task-management-network

volumes:
  mongodb_data:

networks:
  task-management-network:
    driver: bridge